### ISSUE TITLE
Need Login warning appears in chat after being afk for a while

### ISSUE THREAD

**Issue by revelsix** [Moseco/dgg#1]
You can try reproducing it by connecting to chat, then swapping to another app for a while (like 30+ minutes) and when you come back and try and type something, it will give the warning and refuse to send the message. Reconnecting doesn't work, only force closing and reopening the app.

**Comment by Moseco** [comment]
To make it easier for me to find the problem, can you answer a couple questions?

1, Where does the error message appear? In the chat with other messages?
2. Do you have the exact message that is shown?

**Comment by revelsix** [comment]
iirc (trying to reproduce it right now to confirm) it appears in chat kind of like the Connected info card. It's red and I believe all it says is NeedsLogin or NeedLogin

**Comment by Moseco** [comment]
I think I found where the error comes from. [The Dgg server sends the error message if you are not logged in.](https://github.com/destinygg/chat/blob/df26c113dce83af6a6d902d229d7e9f8823e45ea/connection.go#L439)

So I guess the connection gets messed up if you are inactive for a while. Hopefully shouldn't be too hard to fix now that I know why/where it comes from.

**Comment by Moseco** [comment]
@revelsix Hopefully the commit I just added fixes the issue. I will publish an update to the Play Store in the coming week.
