### ISSUE TITLE
Links don't open if there is a native app for them

### ISSUE THREAD

**Issue by alecshackett** [Moseco/dgg#3]
Lately I have noticed clicking on links (youtube, imgur, etc.) do not open in either the respective app or web browser. It simply says "Cannot open link, copied to clipboard."  When I deleted imgur from my phone imgur links started opening in the Chrome browser again successfully.

**Comment by Moseco** [comment]
Thanks for making an issue for this. I'll look into why this is happening and see if I can make a fix for the next update.

**Comment by Moseco** [comment]
Pretty sure I found the problem. [As of Android 11](https://developer.android.com/about/versions/11/privacy/package-visibility) there are restrictions on package visibility. But I made the fix talked about [here](https://github.com/flutter/flutter/issues/63727#issuecomment-736120631) so it should work now. 

I will publish an update to the Play Store this week and close the issue. If after the update you are still having trouble please let me know.
