### ISSUE TITLE
Protocolerror

### ISSUE THREAD

**Issue by alecshackett** [Moseco/dgg#4]
Whenever I include a \ in a message I get a protocol error and the message never goes through. It seems like it can be anywhere throughout the string and not just the first character.

Eg. "\ widepeepoHappy /"

**Comment by Moseco** [comment]
Thanks for creating an issue for this!

I'll start looking into it and see what I can find.

**Comment by Moseco** [comment]
Fixed the bug. It was caused by "\" not being escaped correctly. 

I will publish an update to Google Play today and hopefully it will roll out within the next couple days.
