### ISSUE TITLE
"NODDERS" emote causes giant grey box to fill chat

### ISSUE THREAD

**Issue by Mojavve** [Moseco/dgg#8]
I'm not entirely sure when this started but I only noticed it after the Halloween emotes were enabled.

I've only verified that this happens with NODDERS, every other emote seems to work.  This grey box takes up a massive amount of room, I have never been able to scroll above it.

[Example screenshot](https://i.imgur.com/qVTDP2R.png)

**Comment by Moseco** [comment]
@Mojavve Thanks for reporting the issue. 

I have already created a fix for it and uploaded an update to the Play Store, just waiting for Google to approve it. Usually a review takes less than 24 hours.
